name: DocFX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Setup DocFX
      run: choco install docfx -y
    - name: Generate documentation site
      run: docfx
